In [1]:
import numpy as np

In [2]:
print("HELLO")

HELLO


In [3]:
myarr=np.array([12,3,4,4],np.int64)

In [4]:
myarr

array([12,  3,  4,  4], dtype=int64)

In [5]:
myarr[0]

12

In [8]:
myarr=np.array([[12,3,4,4]],np.int64)

In [9]:
myarr

array([[12,  3,  4,  4]], dtype=int64)

In [10]:
myarr[0,1]

3

In [12]:
myarr.shape

(1, 4)

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr[0,1]=23

In [15]:
myarr

array([[12, 23,  4,  4]], dtype=int64)